version: '3.8'
services:
  EagleDocs:
    image: pixlgalaxy/eagledocsfe:latest
    container_name: EagleDocs
    restart: always
    ports:
      - "3000:80"
    environment:
      - LLM_API_URL="https://[SERVER API ENDPOINT]/api/chat"
      - LLM_MODEL="llama3.1:8b-instruct-fp16"